name: Terraform Integration and Deployment

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/tf-app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.out

      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tf-app/tfplan.out

  terraform-apply:
    name: Terraform Apply (on merge)
    needs: terraform-plan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: infra/tf-app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/tf-app

      - name: Terraform Apply
        run: terraform apply tfplan.out
